### ISSUE TITLE
 Feature request: deflate support

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-site#15]
Originally reported by @AohRveTPV in browscap/browscap#320:

> Hello, I have been trying to improve downloads of Browscap data in the Browscap Drupal module. It is already possible to use gzip compression with the download links, which reduces download size by a factor of 10-20x. However, gzip support is only available in PHP 5.4.0, and Drupal supports earlier versions of PHP.

> If the browscap.org had support for deflate, all Drupal-supported PHP versions would support compression, and the Browscap Drupal module could exclusively use it. Since there are ~11000 sites using the Browscap module, a rough calculation indicates this would potentially save 65GB of traffic to http://browscap.org each time a new dataset is released.

> I am not totally certain this would work, but wanted to put forth the feature request to see if it is something the Browscap project might be willing to add. http://browscap.org seems to be using Apache, and there is mod_deflate for Apache.

> In any case, thank you for providing all the Browscap data.

**Comment by asgrim** [comment]
Deflate is already implemented

**Comment by AohRveTPV** [comment]
Thanks for updating the issue, but I just tested with http://www.browscap.org/stream?q=PHP_BrowsCapINI and deflate still doesn't seem to be working.  Only gzip works.

One way to reproduce:
1. In Firefox, download http://www.browscap.org/stream?q=PHP_BrowsCapINI and observe that only portion of full file size is downloaded (currently ~660KB).
2. Go to about:config, and set `network.http.accept-encoding` to just `deflate`, removing `gzip`.
3. Download http://www.browscap.org/stream?q=PHP_BrowsCapINI and observe full size of file is downloaded (currently ~16MB).

This test page seems to confirm that only gzip is supported:
http://www.gidnetwork.com/tools/gzip-test.php

**Comment by asgrim** [comment]
Hmm, not sure why this isn't working then:

```
$ sudo a2enmod deflate
Considering dependency filter for deflate:
Module filter already enabled
Module deflate already enabled
```

It may be because we use Cloudflare. I've looked, but can't find a way to enable deflate in CF (if anyone knows, please do let me know, as am happy to enable). A small saving of 65GB/month would help a little (although, not much compared to the 3 or 4TB a month we currently consume!)
