### ISSUE TITLE
Travis builds receive Too Many Requests errors

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-site#19]
The browscap builds on Travis often become broken due to hitting the usage cap.

e.g. https://travis-ci.org/browscap/browscap-php/builds/78827251

Find a good solution that doesn't open a security hole for this

**Comment by asgrim** [comment]
Proposed solution for this:
* Add an option to bypass rate limiting
* Bypass rate limiting when a header `X-Browscap-BypassRL: %token%` is used
* Generate a `%token%`, store this in config (not in repo :wink:)
* Update browscap/browscap-php builds to use these tokens using the `env.global.secure` setting in `.travis.yml`

**Comment by mimmi20** [comment]
@asgrim I think If we put a security token into the .travis.yml its not secure anymore.

**Comment by asgrim** [comment]
@mimmi40 it is encrypted, and cannot be re-used outside of Travis (it is a
feature of Travis-CI designed for things like this) :)

**Comment by asgrim** [comment]
@mimmi20 see http://docs.travis-ci.com/user/environment-variables/#Encrypted-Variables

**Comment by mimmi20** [comment]
@asgrim Then I would use one of the last two proposed solutions. The other two may leak out and make the rate limit useless.

**Comment by asgrim** [comment]
@mimmi20 all 4 steps are necessary ;) if the token leaks, I'll notice very quickly (I have many alerts set up), so I simply change the token on the server (no code change necessary, only config.

**Comment by mimmi20** [comment]
@asgrim Ok.

**Comment by asgrim** [comment]
Resolved by caching browscap.ini - see browscap/browscap-php#99
