### ISSUE TITLE
Automate file release process?

### ISSUE THREAD

**Issue by jaydiablo** [browscap/browscap-site#38]
I don't know what this process currently entails, so it might be naive of me to assume that it's something that could be automated, but I wanted to discuss the possibility.

Would it be possible to be able to release a new version of the browscap file by updating composer in this project and having travis/circleci build and deploy to Digital Ocean (or whatever it is you're hosting on)?

Might allow us to release on a more regular schedule and do it without your intervention (@asgrim).

Thoughts?

**Comment by DaAwesomeP** [comment]
This is very possible to implement with Travis.

**Comment by asgrim** [comment]
I'm working (in the little free time I have) on moving Browscap to Heroku. I've had some success so far, but it's not ready for prod.

FYI, the process I use (which in theory could be automated, but permissions and all that): https://github.com/browscap/browscap/wiki/Public-release-procedure

**Comment by asgrim** [comment]
In short: yes, I'm already planning to do this :+1:
