### ISSUE TITLE
IP access blocked

### ISSUE THREAD

**Issue by jmeattle** [browscap/browscap-site#445]
We first noticed the block about 20 hours ago. 

We have called the service the same way for 5+ years and this is the first time we've been blocked.

I would be surprised if we tried to download the csv file more than 30 times in any 1 hour period... but I suppose it could be possible if something went wrong which may have led to retries (by automated processes). Otherwise, it should never really go over 10 max.

I would appreciate it if you can please check. All calls are made from IP - `54.208.16.197`. Many thanks!

```
$ curl -I "https://browscap.org/stream?q=BrowsCapCSV"
HTTP/2 403 
date: Fri, 08 Mar 2024 07:59:42 GMT
```

**Comment by jmeattle** [comment]
Yes, it appears to be:

```
$ curl https://browscap.org/stream?q=BrowsCapCSV
<!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">
```

I checked our logs - it seems like our code was throwing a "Net::HTTPFatalError: 500 "Internal Server Error" when trying to download the file a couple of days ago. My guess is that may have led to retries.

**Comment by asgrim** [comment]
> Yes, it appears to be:
> 
> ```
> $ curl https://browscap.org/stream?q=BrowsCapCSV
> <!DOCTYPE html><html lang="en-US"><head><title>Just a moment...</title><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge">
> ```
> 
> I checked our logs - it seems like our code was throwing a `Net::HTTPFatalError: 500 "Internal Server Error"` when trying to download the file a couple of days ago. My guess is that may have led to retries.

Yes; we had a surge in requests on 6th/7th March, which caused a DB limit to be reached (see #444 ).

I've adjusted the site settings on Cloudflare. Please can you try again?

**Comment by jmeattle** [comment]
Works now!  Thanks so much for the quick attention 🤗

**Comment by asgrim** [comment]
Great, thank you!
