### ISSUE TITLE
Auto merge dependabot

### ISSUE THREAD

**Issue by asgrim** [browscap/browscap-site#78]
https://dependabot.com/docs/config-file/#automerged_updates

Look into it... (placeholder issue) 😁

**Comment by asgrim** [comment]
Humm, I'd set this up in `8921b7e` (I thought), but turns out the `automerged_updates` configuration is for version **1** of config only, and I can't find an equivalent version **2** configuration option (and we're using version 2). Needs further investigation.

**Comment by jaydiablo** [comment]
For dependabot v2 I've had success with this mergeme github action: https://github.com/ridedott/merge-me-action

I've seen some other auto-merge github actions as well, like this one: https://github.com/ahmadnassri/action-dependabot-auto-merge but haven't tried any others yet.

**Comment by asgrim** [comment]
@jaydiablo oh nice, yes that looks very helpful, I'll check into that - thank you :)

**Comment by asgrim** [comment]
https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/automating-dependabot-with-github-actions#enable-auto-merge-on-a-pull-request
